import { StyleSheet, Platform } from "react-native";

const colorPalette = {
  bone: "#e5e5e5",
  boneLight: "#f4f4f4",
  cornellRed: "#A51A16FF",
  raisinBlack: "#25282EFF",
  raisinBlackLight: "#a7aaad",
  cornellRed2: "#B81916ff",
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  warning: {
    alignSelf: "center",
    paddingBottom: 5,
    color: colorPalette.cornellRed,
    fontSize: 30,
    marginTop: 30,
  },
  homeDesc: {
    display: "flex",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
    paddingBottom: 15,
    marginTop: 25,
    fontSize: 14,
    fontWeight: 800,
    letterSpacing: 0,
    color: colorPalette.raisinBlack,
    textTransform: "uppercase",
  },
  homeWarning: {
    width: 310,
    textAlign: "justify",
    alignSelf: "center",
  },
  homeSecurity: {
    width: "100%",
    textAlign: "center",
    alignSelf: "center",
    marginTop: 5,
    paddingBottom: 10,
    fontWeight: 700,
    color: colorPalette.cornellRed2,
  },
  mainBtn: {
    backgroundColor: colorPalette.bone,
    display: "flex",
    alignSelf: "center",
    width: "130",
    padding: 5,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 4,
    marginTop: 10,
  },
  mainBtn2: {
    backgroundColor: colorPalette.raisinBlackLight,
    display: "flex",
    alignSelf: "center",
    width: "130",
    padding: 5,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 4,
    marginTop: 10,
  },
  mainBtn3: {
    backgroundColor: colorPalette.raisinBlackLight,
    display: "flex",
    alignSelf: "center",
    width: "100",
    padding: 4,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 4,
    marginTop: 10,
  },
  mainBtnText: {
    textAlign: "center",
    fontWeight: 700,
  },
  charListHeader: {
    width: "100%",
    textAlign: "center",
    alignSelf: "center",
    fontWeight: 800,
    fontSize: 13,
    letterSpacing: 0,
    marginTop: 0,
    color: colorPalette.raisinBlack,
    textTransform: "uppercase",
  },
  charListSub: {
    width: "100%",
    textAlign: "center",
    alignSelf: "center",
    fontWeight: 800,
    fontSize: 10,
    letterSpacing: 0,
    paddingBottom: 0,
    marginTop: 30,
    color: colorPalette.cornellRed,
    textTransform: "uppercase",
  },
  profileHeader: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 800,
    color: colorPalette.cornellRed,
    padding: 20,
    paddingLeft: 30,
  },
  profileIcon: {
    color: colorPalette.raisinBlackLight,
    fontSize: 12,
    paddingRight: 5,
    paddingLeft: 5,
    verticalAlign: "middle",
  },
  largeHeading: {
    fontSize: 50,
    fontStyle: "italic",
    paddingTop: 15,
  },
  italicHeading: {
    fontStyle: "italic",
  },
  headingColor: {
    ...Platform.select({
      android: {
        color: "yellow",
      },
      ios: {
        color: "red",
      },
      default: {
        color: "blue",
      },
    }),
  },
  listContainer: {
    marginLeft: 10,
    marginTop: -40,
  },
  listItem: {
    marginTop: 5,
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: 0,
    fontSize: 12,
    backgroundColor: colorPalette.boneLight,
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    width: 380,
  },
  listBefore: {
    fontWeight: 800,
    fontSize: 10,
    verticalAlign: "middle",
  },
  profileContainer: {
    paddingHorizontal: 20,
    paddingBottom: 50,
  },
  profileList: {
    fontSize: 14,
    backgroundColor: colorPalette.boneLight,
    borderWidth: 1,
    borderColor: colorPalette.bone,
    marginBottom: 5,
    padding: 5,
    marginTop: 5,
    lineHeight: 20,
  },
  profileLabel: {
    fontWeight: 800,
    fontSize: 13,
    textTransform: "uppercase",
    padding: 6,
  },
  bottomBtns: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "center",
    marginTop: 10,
    paddingVertical: 10,
    gap: 10,
  },

  profileWrap: {
    flex: 1,
  },
  input: {
    borderWidth: 1,
    borderColor: colorPalette.bone,
    backgroundColor:colorPalette.boneLight,
    padding: 10,
    marginBottom: 10,
  },
});

export default styles;
